
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://obarfcyegijjejvbsdml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9iYXJmY3llZ2lqamVqdmJzZG1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NjkzNTAsImV4cCI6MjA2NDQ0NTM1MH0.PdFrVnHwyRZejnyP_cazR0grum6jkBIGg1FS0CG6JWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
